name: Build and Deploy to Render

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/bajahaw/multi-tic-tac:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/bajahaw/multi-tic-tac:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render
        run: |
          curl --request POST \
            --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
            --header 'accept: application/json' \
            --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            --header 'content-type: application/json' \
            --data '
          {
            "clearCache": "do_not_clear",
            "imageUrl": "ghcr.io/bajahaw/multi-tic-tac:latest"
          }
          '
